name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]   # pipeline запускается при push в main

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # Нужно, чтобы action получил доступ к твоему коду

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # твой логин
          password: ${{ secrets.DOCKER_PASSWORD_TOKEN }}  # токен
        # Нужно, чтобы action смог пушить образы

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
        # Сборка и пуш Docker image

  deploy:
    name: Deploy to Kubernetes with Helm
    needs: build_and_push   # запуск только после сборки
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code again
        uses: actions/checkout@v3
        # Нужно, чтобы Helm имел доступ к chart

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
        # Дает GitHub Actions доступ к Minikube

      - name: Deploy using Helm
        run: |
          helm upgrade --install flask-app ./flask-app \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/flask-app \
            --set image.tag=v1 \
            --namespace default
        # Обновляет приложение через Helm chart

